//* ---------- AWS ACTION TYPES ----------
export const SET_CREDENTIAL_STATUS_TO_TRUE = 'SET_CREDENTIAL_STATUS_TO_TRUE';
export const SET_CREDENTIAL_STATUS_TO_FALSE = 'SET_CREDENTIAL_STATUS_TO_FALSE';
export const CHECK_CREDENTIALS_TRUE = 'CHECK_CREDENTIALS_TRUE';
export const CHECK_CREDENTIALS_FALSE = 'CHECK_CREDENTIALS_FALSE';

//* ---------- NAVBAR ACTIONS TYPES -------
export const SHOW_CREATE_MENU_BUTTON = 'SHOW_CREATE_MENU_BUTTON';
export const HIDE_CREATE_MENU_BUTTON = 'HIDE_CREATE_MENU_BUTTON';
export const TOGGLE_CREATE_MENU_DROPDOWN = 'TOGGLE_CREATE_MENU_DROPDOWN';
export const HIDE_CREATE_MENU_DROPDOWN = 'HIDE_CREATE_MENU_DROPDOWN';
export const TOGGLE_CREATE_MENU_FORM_ITEM = 'TOGGLE_CREATE_MENU_FORM_ITEM';
export const MENU_FORM_ITEM_TO_SHOW = 'MENU_FORM_ITEM_TO_SHOW';
export const HIDE_CLUSTER_INFO = 'HIDE_CLUSTER_INFO';
export const DISPLAY_CLUSTER_INFO = 'DISPLAY_CLUSTER_INFO';
export const UPDATE_CLUSTER_DATA = 'UPDATE_CLUSTER_DATA';
