// AWS ACTION TYPES
export const SET_NEW_ROLE = 'SET_NEW_ROLE';


// KUBECTL ACTION TYPES
export const SET_NEW_POD = 'SET_NEW_POD';

export const SET_NEW_DEPLOYMENT = 'SET_NEW_DEPLOYMENT';

export const SET_NEW_SERVICE = 'SET_NEW_SERVICE';


// NAVBAR ACTIONS TYPES 

export const SHOW_CREATE_BUTTON = 'SHOW_CREATE_BUTTON';
export const HIDE_CREATE_BUTTON = 'HIDE_CREATE_BUTTON';
export const TOGGLE_CREATE_MENU = 'TOGGLE_CREATE_MENU';
export const HIDE_CREATE_MENU = 'HIDE_CREATE_MENU';
export const TOGGLE_CREATE_MENU_ITEM = 'TOGGLE_CREATE_MENU_ITEM';
export const MENU_ITEM_TO_SHOW = 'MENU_ITEM_TO_SHOW';

export const HIDE_CLUSTER_INFO = 'HIDE_CLUSTER_INFO'
export const DISPLAY_CLUSTER_INFO = 'DISPLAY_CLUSTER_INFO'

